=== Rodez-IUT/dut-info2-filmprovider-LBCHTS/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ELEMENT librairie (entete,livres) >


        <!ELEMENT entete (text)* >
        <!ELEMENT text (#PCDATA | strong | em | img)*>
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT img (#PCDATA)>
        <!ATTLIST img
                src   CDATA #REQUIRED
                title CDATA>


        <!ELEMENT livres (livre)* >
        <!ELEMENT livre (titre, auteurs, description, prix, isbn) >
        <!ELEMENT titre (#PCDATA)>
        <!ELEMENT auteurs (auteur)* | (groupe)* >
        <!ELEMENT auteur (nom, prenom?)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prenom (#PCDATA)>
        <!ELEMENT groupe (direction, membres)*>
        <!ELEMENT direction (nom, prenom?)>
        <!ELEMENT membres (#PCDATA)>
        <!ELEMENT description (#PCDATA | strong | em | img)*>
        <!ELEMENT prix (#PCDATA)>
        <!ATTLIST prix
                devise (euro | livre | dollar) #REQUIRED "euro"
                type   (HT | TTC)              #REQUIRED "HT"
                tva                            #FIXED    "5.5"
        <!ELEMENT isbn (#PCDATA)>
        <!ATTLIST isbn
                xml:space #FIXED "default"

=== Rodez-IUT/dut-info2-filmprovider-LBCHTS/dut-info2-filmprovider-LBCHTS/Part1-XML-DTD/resources/XML3/LibrairieInternet.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd" [
        <!ENTITY  copyright "&#169;Librairie &#38; Internet 2020" >
        ]>

<librairie>
    <entete>
        <text>
            <strong>Librairie d'Internet</strong>
            <em>La passion de la lecture</em>
            &copyright;
        </text>
    </entete>
    <livres>
        <livre isbn="978-1546394075">
            <titre>Joue-moi du Chopin</titre>
            <auteurs>
                <auteur>
                    <nom>Vox</nom>
                    <prenom>Max</prenom>
                </auteur>
            </auteurs>
            <description>
                Après un incendie dévastateur, Dale Lusk se présente à la porte de sa sœur
                avec rien d’autre qu’un caleçon et un imperméable, ayant désespérément besoin de son aide.
                Ayant perdu à la fois son restaurant et son domicile, Dale se retrouve sans travail,
                ni endroit pour vivre. Pendant qu’elle pousse son frère à acheter une nouvelle garde-robe
                pour mieux correspondre à son air de mannequin, Chrissie présente Dale à Al Borkowski.
                Al est désespérément à la recherche d’un colocataire afin d’éviter que sa grand-mère contrôle
                davantage sa vie. Chrissie se rend compte, lorsqu’elle réunit les deux hommes,
                que des étincelles jaillissent et que des changements se profilent dans leur vie.
            </description>
            <prix devise="euro" type="TTC" tva="5.5">15.59</prix>
        </livre>

        <livre isbn="978-2221220184">
            <titre>Les Voraces</titre>
            <auteurs>
                <auteur>
                    <nom>Jauvert</nom>
                    <prenom>Vincent</prenom>
                </auteur>
            </auteurs>
            <description>
                amais sous la Ve République les élites qui dirigent notre pays n'ont été aussi riches et obnubilées par
                l'argent.
                Jamais autant de hauts fonctionnaires n'ont pantouflé à prix d'or dans le privé.
                Jamais autant de ministres n'ont été multimillionnaires.
                Jamais autant de responsables politiques, et non des moindres, ne sont devenus lobbyistes ou avocats
                d'affaires...
                Comment en est-on arrivé là ? Pourquoi la situation a-t-elle empiré sous Macron ?
                Après deux ans d'enquête et grâce à une quarantaine de témoignages inédits, Vincent Jauvert révèle les
                moeurs de ces élites si voraces qui ont pris le pouvoir dans le sillage du nouveau président de la
                République.
                Il décrit leur course à l'argent, leurs campagnes en coulisses pour dissimuler leurs véritables revenus
                et
                leurs conflits d'intérêts. Un document implacable.
            </description>
            <prix devise="euro" type="TTC" tva="5.5">19.00</prix>
        </livre>

        <livre isbn="978-1539710882">
            <titre>Soup Maker Recipe Book: 100 Delicious &amp; Nutritious Soup Recipes </titre>
            <auteurs>
                <auteur>
                    <nom>Green</nom>
                    <prenom>Liana</prenom>
                </auteur>
            </auteurs>
            <description>
                Making your own soup at home is not only rewarding, it’s nutritious and tasty too. By making your own
                soup you control exactly what goes in.
                The soup recipes found in this book have been made in a Morphy Richards Soup Maker, but they can easily
                be made in any other soup maker, or even with a pot on a stove.
                By including an abundance of healthy ingredients you will do wonders for both your health and well- being.
                Soups are a fantastic way to lose weight – they are usually high in fibre but low in fat and calories.
                In fact, I have included the calorie count of each of the 100 soup recipes found in this book.
            </description>
            <prix devise="livre" type="TTC" tva="5.5">4.99</prix>
        </livre>

        <livre isbn="978-1984877499">
            <titre>A Very Stable Genius: Donald J. Trump's Testing of America</titre>
            <auteurs>
                <auteur>

                </auteur>
            </auteurs>
            <description>
                Washington Post national investigative reporter Carol Leonnig and White House bureau chief Philip Rucker,
                both Pulitzer Prize winners, provide the definitive insider narrative of Donald Trump's unique presidency
                with shocking new reporting and insight into its implications.

                “I alone can fix it.” So went Donald J. Trump’s march to the presidency on July 21, 2016, when he accepted
                the Republican presidential nomination in Cleveland, promising to restore what he described as a fallen
                nation. Yet over the subsequent years, as he has undertaken the actual work of the commander in chief,
                it has been hard to see beyond the daily chaos of scandal, investigation, and constant bluster. It would
                be all too easy to mistake Trump’s first term for one of pure and uninhibited chaos, but there were
                patterns to his behavior and that of his associates. The universal value of the Trump administration is
                loyalty - not to the country, but to the president himself - and Trump’s North Star has been the perpetuation
                of his own power, even when it meant imperiling our shaky and mistrustful democracy.

                Leonnig and Rucker, with deep and unmatched sources throughout Washington, D.C., tell of rages and
                frenzies but also moments of courage and perseverance. Relying on scores of exclusive new interviews with
                some of the most senior members of the Trump administration and other firsthand witnesses, the authors
                reveal the forty-fifth president up close, taking readers inside Robert Mueller’s Russia investigation
                as well as the president’s own haphazard but ultimately successful legal defense. Here for the first time
                certain officials who have felt honor-bound not to publicly criticize a sitting president or to divulge
                what they witnessed in a position of trust tell the truth for the benefit of history.

                This peerless and gripping narrative reveals President Trump at his most unvarnished and exposes how
                decision making in his administration has been driven by a reflexive logic of self-preservation and
                self-aggrandizement - but a logic nonetheless. This is the story of how an unparalleled president has
                scrambled to survive and tested the strength of America’s democracy and its common heart as a nation.
            </description>
            <prix devise="dollar" type="TTC" tva="5.5">18.26</prix>
        </livre>

        <livre isbn="0316497541">
            <titre>The Last Wish: Introducing the Witcher</titre>
            <auteurs>
                <auteur>
                    <nom>Sapkowski</nom>
                    <prenom>Andrzej</prenom>
                </auteur>
            </auteurs>
            <description>
                Geralt is a Witcher, a man whose magic powers, enhanced by long training and a mysterious elixir, have
                made him a brilliant fighter and a merciless assassin. Yet he is no ordinary murderer: his targets are
                the multifarious monsters and vile fiends that ravage the land and attack the innocent.
                But not everything monstrous-looking is evil and not everything fair is good...and in every fairy tale
                there is a grain of truth.
            </description>
            <prix devise="dollar" type="TTC" tva="5.5">17.99</prix>
        </livre>
    </livres>
</librairie>

=== Rodez-IUT/dut-info2-filmprovider-LBCHTS/Part1-XML-DTD/resources/XML3/LibrairieInternet.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE librairie SYSTEM "Part1-XML-DTD/resources/XML3/Librairie.dtd">

<librairie>
    <entete>
        <text>
            <strong>Librairie d'Internet</strong>
            <em>La passion de la lecture</em>
            &amp;copyright;
        </text>
    </entete>
    <livres>
        <livre isbn="978-1546394075">
            <titre>Joue-moi du Chopin</titre>
            <auteurs>
                <auteur>
                    <nom>Vox</nom>
                    <prenom>Max</prenom>
                </auteur>
            </auteurs>
            <description>
                Après un incendie dévastateur, Dale Lusk se présente à la porte de sa sœur
                avec rien d’autre qu’un caleçon et un imperméable, ayant désespérément besoin de son aide.
                Ayant perdu à la fois son restaurant et son domicile, Dale se retrouve sans travail,
                ni endroit pour vivre. Pendant qu’elle pousse son frère à acheter une nouvelle garde-robe
                pour mieux correspondre à son air de mannequin, Chrissie présente Dale à Al Borkowski.
                Al est désespérément à la recherche d’un colocataire afin d’éviter que sa grand-mère contrôle
                davantage sa vie. Chrissie se rend compte, lorsqu’elle réunit les deux hommes,
                que des étincelles jaillissent et que des changements se profilent dans leur vie.
            </description>
            <prix devise="" type="TTC" tva="5.5">15.59</prix>
        </livre>

        <livre isbn="978-1546394075">
            <titre>Les Voraces</titre>
            <auteurs>
                <auteur>
                    <nom>Jauvert</nom>
                    <prenom>Vincent</prenom>
                </auteur>
            </auteurs>
            <description>
                amais sous la Ve République les élites qui dirigent notre pays n'ont été aussi riches et obnubilées par
                l'argent.
                Jamais autant de hauts fonctionnaires n'ont pantouflé à prix d'or dans le privé.
                Jamais autant de ministres n'ont été multimillionnaires.
                Jamais autant de responsables politiques, et non des moindres, ne sont devenus lobbyistes ou avocats
                d'affaires...
                Comment en est-on arrivé là ? Pourquoi la situation a-t-elle empiré sous Macron ?
                Après deux ans d'enquête et grâce à une quarantaine de témoignages inédits, Vincent Jauvert révèle les
                moeurs de ces élites si voraces qui ont pris le pouvoir dans le sillage du nouveau président de la
                République.
                Il décrit leur course à l'argent, leurs campagnes en coulisses pour dissimuler leurs véritables revenus
                et
                leurs conflits d'intérêts. Un document implacable.
            </description>
            <prix devise="euro" type="TTC" tva="5.5">19</prix>
        </livre>

        <livre isbn="978-1546394075">
            <titre>Joue-moi du Chopin</titre>
            <auteurs>
                <auteur>
                    <nom>Vox</nom>
                    <prenom>Max</prenom>
                </auteur>
            </auteurs>
            <description>
                Après un incendie dévastateur, Dale Lusk se présente à la porte de sa sœur
                avec rien d’autre qu’un caleçon et un imperméable, ayant désespérément besoin de son aide.
                Ayant perdu à la fois son restaurant et son domicile, Dale se retrouve sans travail,
                ni endroit pour vivre. Pendant qu’elle pousse son frère à acheter une nouvelle garde-robe
                pour mieux correspondre à son air de mannequin, Chrissie présente Dale à Al Borkowski.
                Al est désespérément à la recherche d’un colocataire afin d’éviter que sa grand-mère contrôle
                davantage sa vie. Chrissie se rend compte, lorsqu’elle réunit les deux hommes,
                que des étincelles jaillissent et que des changements se profilent dans leur vie.
            </description>
            <prix devise="euro" type="TTC" tva="5.5">15.59</prix>
        </livre>

        <livre isbn="978-1546394075">
            <titre>Joue-moi du Chopin</titre>
            <auteurs>
                <auteur>
                    <nom>Vox</nom>
                    <prenom>Max</prenom>
                </auteur>
            </auteurs>
            <description>
                Après un incendie dévastateur, Dale Lusk se présente à la porte de sa sœur
                avec rien d’autre qu’un caleçon et un imperméable, ayant désespérément besoin de son aide.
                Ayant perdu à la fois son restaurant et son domicile, Dale se retrouve sans travail,
                ni endroit pour vivre. Pendant qu’elle pousse son frère à acheter une nouvelle garde-robe
                pour mieux correspondre à son air de mannequin, Chrissie présente Dale à Al Borkowski.
                Al est désespérément à la recherche d’un colocataire afin d’éviter que sa grand-mère contrôle
                davantage sa vie. Chrissie se rend compte, lorsqu’elle réunit les deux hommes,
                que des étincelles jaillissent et que des changements se profilent dans leur vie.
            </description>
            <prix devise="euro" type="HT" tva="5.5">15.59</prix>
        </livre>

        <livre isbn="978-1546394075">
            <titre>Joue-moi du Chopin</titre>
            <auteurs>
                <auteur>
                    <nom>Vox</nom>
                    <prenom>Max</prenom>
                </auteur>
            </auteurs>
            <description>
                Après un incendie dévastateur, Dale Lusk se présente à la porte de sa sœur
                avec rien d’autre qu’un caleçon et un imperméable, ayant désespérément besoin de son aide.
                Ayant perdu à la fois son restaurant et son domicile, Dale se retrouve sans travail,
                ni endroit pour vivre. Pendant qu’elle pousse son frère à acheter une nouvelle garde-robe
                pour mieux correspondre à son air de mannequin, Chrissie présente Dale à Al Borkowski.
                Al est désespérément à la recherche d’un colocataire afin d’éviter que sa grand-mère contrôle
                davantage sa vie. Chrissie se rend compte, lorsqu’elle réunit les deux hommes,
                que des étincelles jaillissent et que des changements se profilent dans leur vie.
            </description>
            <prix devise="euro" type="HT" tva="5.5">15.59</prix>
        </livre>
    </livres>
</librairie>
